Class {
	#name : #PharoTutorial,
	#superclass : #Object,
	#category : #'OnlineHelp-Core-Engine'
}

{ #category : #'as yet unclassified' }
PharoTutorial class >> tutorial1 [
	<onlineTutorial: 'Quick Start' description: 'Overview of the Pharo environment and the tools. You will learn how to use the Pharo environment.'>
	
	 ^#(tutorial1Page1)
]

{ #category : #'as yet unclassified' }
PharoTutorial class >> tutorial1Page1 [
	^'
	
	
	'
]

{ #category : #'as yet unclassified' }
PharoTutorial class >> tutorial2 [
	<onlineTutorial: 'Smalltalk Introduction' description: 'An introduction into the Smalltalk programming language.'>
]
